local record Bit
   band: function(integer, integer): integer
   bor: function(integer, integer): integer
   bxor: function(integer, integer): integer
   lshift: function(integer, integer): integer
   rshift: function(integer, integer): integer
   arshift: function(integer, integer): integer
   rol: function(integer, integer): integer
   ror: function(integer, integer): integer
   bswap: function(integer): integer
end
return Bit
